language: python
sudo: false
python:
 - 3.6
 - "3.7-dev"
 - "nightly"

branches:
  only:
  - master

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
      - gcc-4.5
      - gcc-4.9
      - gcc-5
      - gcc-6

env:
  - DJANGO_VERSION=1.11.1
  - DJANGO_VERSION=1.11.2

install:
  - pip install -q Django==$DJANGO_VERSION
  - travis_wait 30 pip install -r dev_requirements.txt

notifications:
  email:
    on_success: never
    on_failure: always

script:
    - echo "TODO"
