language: python
sudo: false
python:
 - 3.6
 - "3.7-dev"

branches:
  only:
  - master

matrix:
    include:
      - os: linux
        dist: trusty
      - os: linux
        dist: xenial
      - os: linux
        dist: yakkety
      - os: linux
        dist: zesty

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
      - gcc-4.5
      - gcc-4.9
      - gcc-5
      - gcc-6
      - gfortran
      - libopenblas-dev
      - liblapack-dev
      - libatlas-base-dev
      - python3-dev
      - libmysqlclient-dev
      - postgresql-devel

env:
  - DJANGO_VERSION=1.11.1
  - DJANGO_VERSION=1.11.2

install:
  - pip install -q Django==$DJANGO_VERSION
  - travis_wait 30 pip install -r dev_requirements.txt

notifications:
  email:
    on_success: never
    on_failure: always

script:
    - echo "TODO"
