- name: Update cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Upgrade all packages to the latest version
  apt:
    name: "*"
    state: latest

- name: Upgrade dist to latest version
  apt:
    upgrade: dist

- name: install nginx
  apt:
    name: nginx
    state: latest
    update_cache: yes

- name: Install a .deb package from the internet.
  apt:
    deb: https://example.com/python-ppq_0.1-1_all.deb

- name: Remove useless packages from the cache
  apt:
    autoclean: yes

- name: Remove dependencies that are no longer required
  apt:
    autoremove: yes
